export default {
    BANNER_HEADING: "CONNECT WITH YOUR STAR",
    TV: "TV",
    SELECT: "SELECT",
    SUBSCRIBE: "SUBSCRIBE",
    ENJOY: "ENJOY",
    WHAT_YOU_WILL_GET: "WHAT YOU WILL GET",
    DETAILS1: "Exclusive daily videos",
    DETAILS2: "Exclusive live videos",
    DETAILS3: "Real life insights",
    REQUEST: "REQUEST",
    SURPRISE: "SURPRISE",
    CHANNELS: "CHANNELS",
    VIDEO_MESSAGES: 'VIDEO MESSAGES',
    PERSONALISED: "Personalised",
    VIDEO_MESSAGES: "video messages",
    SUITABLE: "Suitable",
    FOR_EVERY_MOMENT: "for every moment",
    TITLE_3: "Every transaction will support charity"
}