export default {
    SOCIAL: 'SOCIAL',
    STREAM: 'STREAM',
    LOGIN: 'Log in',
    SIGNUP: 'Sign up',
    OR: 'Or',
    STAR_PROFILE: 'Star profile',
    VIP_PROFILE: 'VIP Profile',
    GOLD: 'GOLD',
    LOGIN_WITH: 'Log in with',
    SIGNUP_WITH: 'Signup With',
    ADD_PROFILE_PIC: 'Add profile pic',
    FULL_NAME: 'Full Name',
    USERNAME: 'Username',
    EMAIL: 'Email',
    NEXT: 'Next',
    EMAIL_OFFERS: 'Email me exclusive offers and discounts',
    PASSWORD: 'Password',
    REPEAT_PASSWORD: 'Repeat password ',
    ENTER_PASSCODE: 'Enter passcode',
    ENTER_PASSCODE_TITLE: 'Please enter your passcode',
    CANCEL: 'Cancel',
    ACCOUNT_SETTINGS: 'Account settings',
    PROFILE_SETTINGS: 'Profile setting',
    PROFILE_PRICTURE: 'Profile picture',
    NAME_DESCRIPTION: 'Name and description',
    NAME: 'Name',
    DESCRIPTION: 'Description',
    UPDATE: 'Update',
    ENTER_YOUR_EMAIL: 'Enter Your Email',
    OPEN_CAMERA: 'Open camera',
    UPLOAD_IMAGE: 'Upload image',
    SELECT_ALL_THAT_APPLY: '*Select all that apply',
    SELECT_YOUR_CATEGORY: 'Select your category',
    BANK_DETAILS: 'Bank details',
    SELECT_ACCOUNT: 'Select account',
    ADD_ACCOUNT: 'Add account',
    ADD_CARD: 'ADD CARD',
    DELETE: 'Delete',
    CARD: 'Card',
    BANK_ACCOUNT: 'Bank Account',
    CARD_HOLDER: 'CARD HOLDER',
    CARD_NUMBER: 'XXXX XXXX XXXX XXXX',
    CVV: 'CVV',
    EXPIRY: 'MM/YY',

    BANK_ACCOUNT_NUMBER: 'BANK ACCOUNT NUMBER',
    ROUNTING_NUMBER: 'ROUTING NUMBER',
    CURRENCY: 'CURRENCY',
    ACCOUNT_HOLDER: 'ACCOUNT HOLDER',
    SUBSCRIPTION: 'Subscriptions',
    NOTIFICATION: 'Notification',
    ON: 'ON',
    OFF: 'OFF',
    THEME: 'Theme',
    DARK: 'DARK',
    LIGHT: 'LIGHT',
    SECURITY_PRIVACY: 'Security & Privacy',
    TERMS_OF_SERVICE: 'Terms of service',
    FAQ: 'FAQ',
    WATCH_VIDEO: 'Watch Video',
    PERSONAL_VIP_CODE: 'Enter your super secret personal VIP code',
    VIP_CODE: 'VIP Code',
    UPLOAD_VIDEO_INTRO: 'Upload video intro',
    DO_IT_LATER: 'Do it later',
    UPLOAD_THUMBLIN_IMAGE: 'Upload Thumbnail image',
    SUBSCRIBED: 'Subscribed'
}